### ISSUE TITLE
Jonshema of workflow block fails without "unused import"

### ISSUE THREAD

**Issue by masfaraud** [Dessia-tech/dessia_common#205] opened 2022-03-21 18:22 UTC
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
Jsonschema of some blocks in workflow fails without VariableWithDefaultValue import in workflow/blocks.py (but is unused)

```
Traceback (most recent call last):

  File "/home/masfaraud/Documents/DessiA/git/dessia_common/dessia_common/models/workflows/vectored_workflow.py", line 66, in <module>
    print(block.jsonschema())

  File "/home/masfaraud/Documents/DessiA/git/dessia_common/dessia_common/core.py", line 290, in jsonschema
    annotations = get_type_hints(init)

  File "/usr/lib/python3.8/typing.py", line 1264, in get_type_hints
    value = _eval_type(value, globalns, localns)

  File "/usr/lib/python3.8/typing.py", line 272, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)

  File "/usr/lib/python3.8/typing.py", line 272, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)

  File "/usr/lib/python3.8/typing.py", line 272, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)

  File "/usr/lib/python3.8/typing.py", line 272, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)

  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)

  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),

  File "<string>", line 1, in <module>

NameError: name 'VariableWithDefaultValue' is not defined
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** Avoid reference to other packages

Remove unused import of VariableWithDefaultValue in workflow/blocks.py 
Run test tests/workflow/blocks.py

* **Possible fixes**

* **Please tell us about your environment:**
  
  - branch: testing

**Comment by GhislainJ** [comment] 2023-02-13 13:53
I am closing this as I cannot reproduce it and is soon to be a deprecated tests anyway

**Closed by GhislainJ** 2023-02-13 13:53 UTC
Labels: Type: Bug, Status: Cannot reproduce, Status: Investigation needed
