### ISSUE TITLE
wfrun._check_platform not valid with exec time

### ISSUE THREAD

**Issue by MackJoly** [Dessia-tech/dessia_common#387] opened 2022-10-04 19:44 UTC
**Note: for support questions, please use https://nextcloud.dessia.tech/call/hr9z9bif

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request

* **What is the current behavior?**

workflow10_run._check_platform()

```
C:\Users\Mack\Documents\git\dessia_common\dessia_common\utils\serialization.py:236: Warning: specific to_dict of class InstantiateModel should implement use_pointers, memo and path arguments
  warnings.warn(f'specific to_dict of class {class_.__name__} '
C:\Users\Mack\Documents\git\dessia_common\dessia_common\utils\serialization.py:236: Warning: specific to_dict of class ModelMethod should implement use_pointers, memo and path arguments
  warnings.warn(f'specific to_dict of class {class_.__name__} '
C:\Users\Mack\Documents\git\dessia_common\dessia_common\utils\serialization.py:236: Warning: specific to_dict of class ModelAttribute should implement use_pointers, memo and path arguments
  warnings.warn(f'specific to_dict of class {class_.__name__} '
C:\Users\Mack\Documents\git\dessia_common\dessia_common\utils\serialization.py:236: Warning: specific to_dict of class Archive should implement use_pointers, memo and path arguments
  warnings.warn(f'specific to_dict of class {class_.__name__} '
data diff:  object_print Different values:		#/execution_time: values differ 457.4781975746155 / 1134.8847694396973
Missing attributes:		#/values: missing in second object
Different values:		#/execution_time: values differ 457.4781975746155 / 1134.8847694396973
Missing attributes:		#/values: missing in second object
Traceback (most recent call last):
  File "C:\Users\Mack\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\Mack\Documents\git\dessia_common\dessia_common\core.py", line 610, in _check_platform
    raise dessia_common.errors.DeserializationError('Object is not equal to itself'
dessia_common.errors.DeserializationError: Object is not equal to itself after serialization/deserialization
```
 Is there a problem here ?

  
  - branch: feat/diff-objects
  - commit:  
  - python version:

**Comment by younesdessia** [comment] 2022-12-07 10:46
@GhislainJ 
Reproduced in another case, which is not simple.
Developing a simple case

**Comment by younesdessia** [comment] 2022-12-07 11:07
`/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/utils/serialization.py:235: Warning: specific to_dict of class InstantiateModel should implement use_pointers, memo and path arguments
  warnings.warn(f'specific to_dict of class {class_.__name__} '
/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/utils/serialization.py:235: Warning: specific to_dict of class ModelMethod should implement use_pointers, memo and path arguments
  warnings.warn(f'specific to_dict of class {class_.__name__} '
/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/utils/serialization.py:235: Warning: specific to_dict of class ModelAttribute should implement use_pointers, memo and path arguments
  warnings.warn(f'specific to_dict of class {class_.__name__} '
data diff:  ([('#/execution_time', 1332.5417168140411, 1736.626187324524)], [], [])
Traceback (most recent call last):
  File "/home/younes/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-59f12355cbc4>", line 1, in <cell line: 1>
    workflow_run._check_platform()
  File "/home/younes/Bureau/DESSIA_WORK/dessia_common/dessia_common/core.py", line 620, in _check_platform
    raise dessia_common.errors.DeserializationError('Object is not equal to itself'
dessia_common.errors.DeserializationError: Object is not equal to itself after serialization/deserialization`

**Comment by GhislainJ** [comment] 2023-02-02 10:17
@MackJoly & @younesdessia Do you have any more info on this ? I still cannot reproduce and will close the issue soon, in that case

**Comment by MackJoly** [comment] 2023-02-02 11:39
You can close it, I am sorry for the unresponse

**Closed** 2023-02-13 12:05 UTC
Labels: Type: Bug, Status: Cannot reproduce, Status: Investigation needed
